/optimizer/order7/weight_T: 2024.0
/optimizer/order7/weight_acc:  16.0
/optimizer/order7/weight_jerk: 0.2
/optimizer/order7/weight_snap: 0.001
#/optimizer/weight_acc:  0.0
#/optimizer/weight_jerk: 0.0
#/optimizer/weight_snap: 0.1
/optimizer/order7/max_a: 3.0
/optimizer/order7/max_v: 5.0
/optimizer/order7/max_it: 23
/optimizer/order7/eps: 0.02

/optimizer/order5/weight_T: 2024.0
/optimizer/order5/weight_acc:  16.0
/optimizer/order5/weight_jerk: 0.2
/optimizer/order5/weight_snap: 0.0
#/optimizer/weight_acc:  0.0
#/optimizer/weight_jerk: 0.0
#/optimizer/weight_snap: 0.1
/optimizer/order5/max_a: 2
/optimizer/order5/max_v: 5
/optimizer/order5/max_it: 23
/optimizer/order5/eps: 0.05

/manager/use_order_5: true
/manager/use_order_7: true